name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ "Windows", "macOS", "Linux", "iOS", "Android", "Web" ]
        include:
          - platform: "Windows"
            runs-on: "windows-latest"
          - platform: "macOS"
            runs-on: "macos-latest"
          - platform: "Linux"
            runs-on: "ubuntu-latest"
            briefcase-args: "--target ubuntu:24.04"
          - platform: "iOS"
            runs-on: "macos-latest"
          - platform: "Android"
            runs-on: "ubuntu-latest"
          - platform: "Web"
            runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Briefcase
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install briefcase

      - name: Build App
        run: briefcase build ${{ matrix.platform }} ${{ matrix.briefcase-args }} --no-input

      - name: Package App
        run: briefcase package ${{ matrix.platform }} ${{ matrix.briefcase-args }} --adhoc-sign --no-input

      - name: Upload App
        if: matrix.platform != 'iOS'
        uses: actions/upload-artifact@v4
        with:
          name: App-${{ matrix.platform }}
          path: 'dist'
          if-no-files-found: error
